-- ★구역별 어택/방어★ (2026-09-17 사장님)
--
--   A · B · 2층 · 숏 넷을 라운드마다 따로 판정해 쌓는다.
--   한 칸 = (그 선수가 낀 한 라운드 × 한 구역). 그래서 라운드 하나가 0~4칸 들어간다.
--
--   N  분모 — 그 구역에서 그 선수가 킬이나 데스를 낸 라운드 수 (판정된 것만)
--   Ok 분자 — 어택이면 ★뚫은★ 칸 · 방어면 ★안 뚫린★ 칸
--
--   개인 육각이 쓰는 것
--     스나  A어택(aAtk) · B어택(bAtk) · A방어(aDef)
--     라플  어택성공률 = (bAtk + f2Atk + shortAtk) · 방어율 = (bDef + f2Def + shortDef)
--           ★A 는 안 넣는다★ — A 단독 승률 70.3% 로 넷 중 꼴찌이고 선수 46%가 분모 10 미만이다.
--           A 를 빼면 납득 안 가는 판 설명력이 88.2% → 90.4% 로 오른다 (전 후보 중 1위).
--
--   옛 칸은 하나도 안 건드린다 (`CLAUDE.md` 1-4).
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "aAtkN"      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "aAtkOk"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "aDefN"      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "aDefOk"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "bAtkN"      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "bAtkOk"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "bDefN"      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "bDefOk"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "f2AtkN"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "f2AtkOk"    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "f2DefN"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "f2DefOk"    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "shortAtkN"  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "shortAtkOk" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "shortDefN"  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "shortDefOk" INTEGER NOT NULL DEFAULT 0;

-- ★자리(포지션) 재료★ — 선수별 시즌 합으로 자리를 정한다 (`sideAxes.ts` 의 `positionOf`).
--   개인 육각은 자리를 ★안 쓴다★ (사장님이 어택성공률로 통일하셨다). 화면 이름표용이다.
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "seatSpots"      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "seatBSpots"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "seatF2Spots"    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "seatShortSpots" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "MatchPlayerHex" ADD COLUMN IF NOT EXISTS "sniperKills"    INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "aAtkN"      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "aAtkOk"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "aDefN"      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "aDefOk"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "bAtkN"      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "bAtkOk"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "bDefN"      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "bDefOk"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "f2AtkN"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "f2AtkOk"    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "f2DefN"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "f2DefOk"    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "shortAtkN"  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "shortAtkOk" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "shortDefN"  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "shortDefOk" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "seatSpots"      INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "seatBSpots"     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "seatF2Spots"    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "seatShortSpots" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "sniperKills"    INTEGER NOT NULL DEFAULT 0;
-- 자리는 시즌 줄에만 적는다 — 경기 하나로는 못 정한다 (경기별 배정은 최빈 69.8%로 흔들렸다)
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "seat"      TEXT;
ALTER TABLE "LeaguePlayerHex" ADD COLUMN IF NOT EXISTS "seatRatio" DOUBLE PRECISION;
