ALTER TABLE "LeaguePlayer" ADD COLUMN IF NOT EXISTS "scoreRating" INTEGER;
ALTER TABLE "LeaguePlayer" ADD COLUMN IF NOT EXISTS "scoreGames" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayer" ADD COLUMN IF NOT EXISTS "scoreTotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayer" ADD COLUMN IF NOT EXISTS "scoreBonus" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "LeaguePlayer" ADD COLUMN IF NOT EXISTS "scoredAt" TIMESTAMP(3);
